##### 公共 配置 #######

#内置Tomcat容器配置
server:
  port: 8888
  servlet:
    #应用路径，配置应用路径，可方便进行反向代理
    context-path:
#    context-path: /baseadmin
#基础配置
spring:
  profiles:
    active: ${BASE_ADMIN:dev} #选择配置分支，先读取系统环境变量，如果没有则默认值为 dev
  application:
    name: analysis_of_transferred_cases

  #修改thymeleaf访问根路径
  thymeleaf:
    prefix: classpath:/view/
    cache: false

  #mvc接收参数时对日期进行格式化
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  #jackson对响应回去的日期参数进行格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #打印SQL
  jpa:
    show-sql: false
    database: oracle
    properties:
      jdbc:
        batch_size: 500
        batch_versioned_data: true
        order_inserts: true
  #文件上传控制
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB

SEND_NAME_NEED_TO_EXCLUDE:
  00U01-金属切削,00U02-塑性加工,00U03-农业印刷,00U05-包装输送,00U06-工程元件,00U07-纺织工程,00U08-建筑道桥,00U09-动力机械,00U10-采矿锁具,00U11-交通运输,00U12-热能,00U13-医疗器械,00U14-测量,00U16-光学影像,00U17-电力工程,00U18-半导体,00U19-电子元器件,00U20-计算机,00U21-通信工程,00U23-化学工程



#是否需要输入验证码
captcha:
  enable: false

---
##### dev 配置 #######
spring:
  profiles: dev

  #数据库配置
  datasource:
    #url: jdbc:mysql://172.17.1.1:3306/test_base_admin?serverTimezone=GMT%2B8&characterEncoding=utf-8
    #username: root
    #password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:oracle:thin:@172.17.0.17:1521:orcl
    #url: jdbc:oracle:thin:@192.168.8.117:1521:orcl
    username: zljg
    password: zljg123456
    driverClassName: oracle.jdbc.driver.OracleDriver


#是否需要输入验证码
captcha:
  enable: false

---
##### prod 配置 #######
spring:
  profiles: prod

  #数据库配置
  datasource:
    url: jdbc:oracle:thin:@192.168.8.117:1521:orcl
    username: zljg
    password: zljg123456
    driverClassName: oracle.jdbc.driver.OracleDriver
  #datasource:
    #url: jdbc:mysql://172.17.0.219:3306/test_base_admin?serverTimezone=GMT%2B8&characterEncoding=utf-8
    #username: root
    #password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver

#是否需要输入验证码
captcha:
  enable: true